# Generated by Django 3.2.4 on 2022-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=True, max_length=50)),
                ('fname', models.CharField(default=True, max_length=50)),
                ('lname', models.CharField(default=True, max_length=50)),
                ('email', models.CharField(default=True, max_length=50)),
                ('password', models.CharField(default=True, max_length=50)),
                ('conf_pass', models.CharField(default=True, max_length=50)),
            ],
        ),
    ]
